import os
from azure.identity import DefaultAzureCredential,ClientSecretCredential
from azure.mgmt.monitor import MonitorManagementClient
from azure.mgmt.network import NetworkManagementClient


def main():
    tenantid = os.environ.get('nonprod_tenantid')
    clientid = os.environ.get('nonprod_clientid')
    clientsecret = os.environ.get('nonprod_clientsecret')

    subscription_id = '166157a8-9ce9-400b-91c7-1d42482b83d6'
    rg_name = "FW-Hybrid-Test"
    applicationgateway_name = "leiappgw01"
    
    clientcredential = ClientSecretCredential(tenantid,clientid,clientsecret)

    network_client = NetworkManagementClient(credential=clientcredential, subscription_id = subscription_id)
    monitor_client = MonitorManagementClient(credential=clientcredential, subscription_id = subscription_id)

    #获得负载均衡器信息
    application_gateway = network_client.application_gateways.get(rg_name,applicationgateway_name)
    resource_id = application_gateway.id

    timespan = '2024-05-23T01:40:00Z/2024-05-23T07:41:00Z'
    metricnamespace = 'Microsoft.Network/loadBalancers'

    #Support Metric
    #https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-network-applicationgateways-metrics


    #拿到负载均衡器后端的ip地址，具体步骤略。
    #我这里后端的ip分别是：10.99.76.10 和10.99.76.14

    #internal PT1H 代表每1小时
    #BackendResponseStatus 代表后端服务是否健康
    #
    result1 = monitor_client.metrics.list(resource_id,timespan,"PT1H","BackendResponseStatus","Count",None,None,"Backendserver eq '10.99.2.5:80'")
  
    print(result1)



if __name__ == '__main__':
    main()

###############################   sample result for Application Gateway
###############################
###############################
###############################
# {
#     "cost": 299,
#     "timespan": "2024-05-23T01:27:00Z/2024-05-23T06:27:00Z",
#     "interval": "PT1H",
#     "value": [
#         {
#             "id": "/subscriptions/166157a8-9ce9-400b-91c7-1d42482b83d6/resourceGroups/FW-Hybrid-Test/providers/Microsoft.Network/applicationGateways/leiappgw01/providers/Microsoft.Insights/metrics/BackendResponseStatus",
#             "type": "Microsoft.Insights/metrics",
#             "name": {
#                 "value": "BackendResponseStatus",
#                 "localizedValue": "Backend Response Status"
#             },
#             "displayDescription": "The number of HTTP response codes generated by the backend members. This does not include any response codes generated by the Application Gateway.",
#             "unit": "Count",
#             "timeseries": [
#                 {
#                     "metadatavalues": [],
#                     "data": [
#                         {
#                             "timeStamp": "2024-05-23T01:27:00Z"
#                         },
#                         {
#                             "timeStamp": "2024-05-23T02:27:00Z"
#                         },
#                         {
#                             "timeStamp": "2024-05-23T03:27:00Z"
#                         },
#                         {
#                             "timeStamp": "2024-05-23T04:27:00Z"
#                         },
#                         {
#                             "timeStamp": "2024-05-23T05:27:00Z",
#                             "count": 810
#                         }
#                     ]
#                 }
#             ],
#             "errorCode": "Success"
#         }
#     ],
#     "namespace": "Microsoft.Network/applicationGateways",
#     "resourceregion": "japaneast"
# }